name: Minha primeira action

on: [ push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validar syntaxe da pasta src
      run: php -l src/
      
    - name: Setup PHP with Xdebug 2.x
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: xdebug2


