name: Minha primeira action

on: [ push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validar syntaxe da pasta src
      run: php -l src/


